### ISSUE TITLE
Reliance on Existing State in Shopify

### ISSUE THREAD

**Issue by DanielWright** [glossier/solidus_retail#5]
The test suite relies on the Shopify shop being in a specific state. This is exceedingly brittle, even as a "private" integration. If the state of the shop changes, or we use a different shop, the tests break. Some ideas:
1. Use WebMock or Fakeweb to generate the desired Shopify API responses. The upside is we have a great level of control over the API responses, they will be very fast, and they eliminate any reliance on Shopify's state. The downside is the tests will not protect the extension from changes to the API behaviour.
2. Use the Shopify API to create any objects needed for acceptance testing. The upside is we exercise the full breadth of the extension, we eliminate reliance on existing state in Shopify, and we're protected from changes to the API behaviour. We can make this solution performant by recording the interactions with VCR. The downside is considerable overhead.

Thoughts?

**Comment by bryanmtl** [comment]
I would vote for option #2 at this point.

**Comment by thisiscab** [comment]
@DanielWright 

#2 was built up from the beginning. The spec suites creates the object in Shopify via the API in order for the test to run and then it destroy those objects to make sure that they are not any test left-overs. Did you experience otherwise?

Changing the Shopify shop or if the "state" of the shop changes all the tests should still be green.

**Comment by DanielWright** [comment]
Hm. When I ran the suite without the "correct" shop credentials, my spec suite failed.

**Comment by thisiscab** [comment]
I have removed VCR due to multiple issues I was hitting, those issues are detailed in their respective commit messages, I needed some help in order to figure out the best way to solve those issues.

But yes, if no cassettes were saved, we are required to have a valid shop in order to correctly create the items on Shopify else I am unsure how we'll be able to retrieve them (if we put VCR aside).

Once the VCR problems are resolved then we'll be good to go.

**Comment by DanielWright** [comment]
The issue is [this line](https://github.com/glossier/solidus_retail/blob/feature/shopify/gateway-implementation/spec/shared/contexts/shopify_shop.rb#L20), which cites a specific line-item ID in the Shopify store. If I use any other store, that line-item won't exist.

**Comment by thisiscab** [comment]
I'll have it double-checked then! :)

**Comment by thisiscab** [comment]
@DanielWright Actually the line-item ID specified is not relevant, it will correctly assign the variant to the product without creating it. It acts like "stub" if you want. 

It doesn't look for that line-item anywhere with how the Shopify API is made.
I am unsure what the problem you were hitting was, but I can't seem to reproduce it.

**Comment by thisiscab** [comment]
This issue can now be closed.
