### ISSUE TITLE
Bundled Products for POS

### ISSUE THREAD

**Issue by thisiscab** [glossier/solidus_retail#7]
Talking about how we wanted to actually implement the bundled products on Shopify opened a bunch of questions about how those bundled products are managed/behaving for the point of sale.

Here are a few questions:
- How will the bundled products be handled? Will it be pre-packaged or it will have to be packaged on the fly?
- Are there rebates the product, meaning will the sum of all the contained product price be more than the actual value of the bundled product?
- How will the stock be managed? There are multiple different skus for the same product with some of them contained "SET". How are those inventory managed? 
- When we sync the order from Shopify to Solidus, do we need to keep the concept of the bundled product?
- Can we return 2 out of 3 products (for example) from a Bundle? 
  - Are the items considered as a bundle or individual from the POS perspective?

**Comment by aamyot** [comment]
- How will the bundled products be handled? Will it be pre-packaged or it will have to be packaged on the fly?
  _We need a sku in Shopify.  We could dynamically create skus for all possible permutations of a bundle based on some convention_
- Are there rebates the product, meaning will the sum of all the contained product price be more than the actual value of the bundled product?
  _Yes, the price of the bundle can be be lower than the sum of its parts_
- How will the stock be managed? There are multiple different skus for the same product with some of them contained "SET". How are those inventory managed? 
  _Not sure about this one.  We created skus with the -SET prefix in order to reserve inventory specifically for sets.  Not sure if it applies here or if we're gonna have a specific inventory/warehouse for retails.  Please enlighten me if you have the answer._
- When we sync the order from Shopify to Solidus, do we need to keep the concept of the bundled product?
  _Yes, we want to keep that concept and have them as bundle in Solidus.  Again, based on the skus when importing from Shopify to Solidus, we could detect when it's a bundle and create the order accordingly._
- Can we return 2 out of 3 products (for example) from a Bundle? 
  _I'm pretty sure we're not doing it right now.  I would not worry with that for now._
- Are the items considered as a bundle or individual from the POS perspective?
  _With a different sku for every permutations, I guess it means they're considered individual items._

**Comment by braidn** [comment]
Current implementation of the POS exporter:

https://github.com/DynamoMTL/glossier.com/blob/master/lib/shopify/generate_pos_order.rb#L65

**Comment by braidn** [comment]
@jshefta I was informed that you created all the old bundles by hand in the previous Shopify incarnation? Do you remember the permutation you used to create the SKU's for these bundles or perhaps have a snapshot of it? We are trying to recreate this in the exporter/importer and would like to keep the SKU transformation kinda the same. Thank you!

**Comment by DanielWright** [comment]
When we discussed this with Bryan a week or so ago, the sense I got was we needed to support two workflows initially:
1. When exporting a bundled product, decompose the comprised permutations into individual Shopify products.
2. When importing a Shopify order, any Set line-item would get converted to the corresponding bundled-product variant.

This seems achievable with a pretty simple convention for SKUs, for example concatenating the bundled-parts' SKUs with dashes.

**Comment by thisiscab** [comment]
![screen shot 2016-09-12 at 10 01 13](https://cloud.githubusercontent.com/assets/1725061/18438583/07e64870-78d0-11e6-94a3-5d57171e4cf1.png)
![screen shot 2016-09-12 at 10 01 39](https://cloud.githubusercontent.com/assets/1725061/18438585/07eb9532-78d0-11e6-9fb5-d9f7b512e78d.png)

This is how it looks like when going into the Production Shopify Shop for Phase 2 Variants.

**Comment by thisiscab** [comment]
The SKU for those variants seem to all be the same.

**Comment by braidn** [comment]
Right, so I think going forward we can't keep these 'Bundled Skus' and have something that decomposes into Solidus. Unless we have some front or back matter of the SKU's along with the name 'Phase2'. Still exploring

**Comment by thisiscab** [comment]
I was thinking to have the SKU for each of those permutation to be something along that:
`{BUNDLE_SKU}/{OPTION1..X}` which would be something like that:
`PHASE2/CAKE/BLOND/LIGHT`

**Comment by braidn** [comment]
That could be very easy to 'exploded on'. Anyone else have some ideas? It's also very easy to look at and understand in the Shopify App. Could it be too long ever?

**Comment by braidn** [comment]
Successfully have a Phase1 order complete locally and will model the items from Shopify to this.

![](http://cloud.godynamo.com/2D3o08251x34/Image%202016-09-12%20at%2012.24.36%20PM.png)

**Comment by thisiscab** [comment]
Instead of giving you the OPTIONS, I'll give you the SKUS.

So it would look something like that:
`PHASE2/GBB100-SET/GML100-SET/GSC100-SET`

**Comment by braidn** [comment]
@cabouffard do you want to change this into a PR with your branch or mine?

**Comment by thisiscab** [comment]
I think it makes more sense to do it for mine. Since your PR will encapsulate every type of orders not just bundle products one.
